PLUGIN_NAME=		trusttunnel
PLUGIN_VERSION=		2.1.0
PLUGIN_COMMENT=		TrustTunnel VPN endpoint (server)
PLUGIN_DEPENDS=		trusttunnel libqrencode
PLUGIN_MAINTAINER=	mpanius@gmail.com
PLUGIN_WWW=		https://github.com/mpanius/opnsense-trusttunnel

.include "${.CURDIR}/../../Mk/plugins.mk"
