PLUGIN_NAME=		trusttunnel-client
PLUGIN_VERSION=		2.1.0
PLUGIN_COMMENT=		TrustTunnel VPN client
PLUGIN_DEPENDS=		trusttunnel-client
PLUGIN_MAINTAINER=	mpanius@gmail.com
PLUGIN_WWW=		https://github.com/mpanius/opnsense-trusttunnel

.include "${.CURDIR}/../../Mk/plugins.mk"
