#!/usr/local/bin/python3
# -*- coding: utf-8 -*-
"""
render_client_config.py — render trusttunnel_client.toml from the
currently active server row in config.xml.

Same Codex-#3 (TOML injection) and Claude-#1 (atomic write) safeguards
as render_server_config.py — reuses the helpers via local import-by-path
(no setuptools needed in the plugin tree).

Inputs:
    /conf/config.xml (read-only) — <OPNsense><trusttunnel><client>...

Outputs:
    /usr/local/etc/trusttunnel/client/trusttunnel_client.toml (0600 — has
    plaintext password for the active server)

Exit codes:
    0   — success
    1   — config invalid (no <client>, no active server, validation fail)
    2   — I/O failure
    65  — active server row references a UUID not in <servers>

Copyright (c) 2026 Mikhail Panyushkin <mpanius@gmail.com>
BSD-2-Clause — see LICENSE.
"""

from __future__ import annotations

import importlib.util
import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

CONFIG_PATH = Path("/conf/config.xml")
OUT_DIR     = Path("/usr/local/etc/trusttunnel/client")
OUT_FILE    = OUT_DIR / "trusttunnel_client.toml"


# Reuse _toml_escape() + _write_atomic() from render_server_config.py.
def _load_helpers():
    here = Path(__file__).parent
    src = here / "render_server_config.py"
    spec = importlib.util.spec_from_file_location("_tt_render_server", str(src))
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load helpers from {src}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod._toml_escape, mod._write_atomic


_toml_escape, _write_atomic = _load_helpers()


def _text(parent: ET.Element, tag: str, default: str = "") -> str:
    el = parent.find(tag)
    if el is None or el.text is None:
        return default
    return el.text


def _bool(parent: ET.Element, tag: str, default: bool = False) -> bool:
    el = parent.find(tag)
    if el is None or el.text is None or el.text == "":
        return default
    return el.text in ("1", "true", "yes")


def _csv(parent: ET.Element, tag: str) -> list[str]:
    el = parent.find(tag)
    if el is None or el.text is None:
        return []
    return [p.strip() for p in el.text.split(",") if p.strip()]


def find_active_server(client: ET.Element) -> ET.Element:
    active = _text(client, "active_server")
    if active == "":
        sys.exit("error: <active_server> empty — pick a server in the UI before Apply")
    servers_node = client.find("servers")
    if servers_node is None:
        sys.exit("error: <servers> missing")
    for srv in servers_node.findall("server"):
        # OPNsense ArrayField rows are addressed by their auto-generated
        # @uuid attribute on the wrapping element. ET stores it as
        # `.attrib['uuid']`.
        if srv.attrib.get("uuid") == active:
            return srv
    # Fall back: some OPNsense versions store uuid as a child element.
    for srv in servers_node.findall("server"):
        if _text(srv, "uuid") == active:
            return srv
    sys.stderr.write(f"error: active_server={active!r} not found in <servers>\n")
    sys.exit(65)


def render_client_toml(client: ET.Element, srv: ET.Element) -> str:
    mode          = _text(client, "mode", "selective")
    tun_iface     = _text(client, "tun_interface", "tt0")
    allowed       = _csv(client, "allowed_destinations")
    hostname      = _text(srv, "hostname")
    addresses     = _csv(srv, "addresses")
    if not addresses:
        # Compose a default address from <hostname>:443.
        addresses = [f"{hostname}:443"]
    custom_sni    = _text(srv, "custom_sni")
    username      = _text(srv, "username")
    password      = _text(srv, "password")
    skip_verify   = _bool(srv, "skip_verification", False)
    upstream      = _text(srv, "upstream_protocol", "http2")
    anti_dpi      = _bool(srv, "anti_dpi", False)
    cli_rnd_prefix = _text(srv, "client_random_prefix")
    dns_upstreams = _csv(srv, "dns_upstreams")
    cert_pem      = _text(srv, "certificate_pem")

    if mode not in ("general", "selective"):
        sys.exit(f"error: mode must be general or selective, got {mode!r}")
    if upstream not in ("http2", "http3"):
        sys.exit(f"error: upstream_protocol must be http2 or http3, got {upstream!r}")
    if username == "" or password == "":
        sys.exit("error: active server missing username/password")
    if hostname == "":
        sys.exit("error: active server missing hostname")

    # Validate username against the same regex the server-side enforces.
    if not all(c.isalnum() or c in "._-" for c in username):
        sys.exit("error: active server username contains forbidden chars")

    lines: list[str] = [
        "# Generated by os-trusttunnel render_client_config.py — do not edit.",
        f"# Mode: {mode}",
    ]

    lines.append("")
    lines.append("[[server]]")
    lines.append(f"hostname = {_toml_escape(hostname)}")
    lines.append("addresses = [" + ", ".join(_toml_escape(a) for a in addresses) + "]")
    if custom_sni:
        lines.append(f"custom_sni = {_toml_escape(custom_sni)}")
    lines.append(f"username = {_toml_escape(username)}")
    lines.append(f"password = {_toml_escape(password)}")
    if skip_verify:
        lines.append("skip_verification = true")
    lines.append(f"upstream_protocol = {_toml_escape(upstream)}")
    if anti_dpi:
        lines.append("anti_dpi = true")
    if cli_rnd_prefix:
        lines.append(f"client_random_prefix = {_toml_escape(cli_rnd_prefix)}")
    if cert_pem:
        # Cert is multi-line PEM; render as TOML literal multi-line string
        # via triple-quoted basic — but our escaper rejects newlines. So
        # write a path-based cert instead: dump PEM to a sibling file and
        # reference it. Atomic write the cert too.
        cert_file = OUT_DIR / "server_cert.pem"
        _write_atomic(cert_file, cert_pem.rstrip() + "\n", 0o644)
        lines.append(f"certificate_path = {_toml_escape(str(cert_file))}")
    if dns_upstreams:
        lines.append("dns_upstreams = [" + ", ".join(_toml_escape(d) for d in dns_upstreams) + "]")

    lines.append("")
    lines.append("[listener.tun]")
    lines.append(f"interface_name = {_toml_escape(tun_iface)}")

    lines.append("")
    lines.append(f"[mode.{mode}]")
    if allowed:
        lines.append("allowed_destinations = [" + ", ".join(_toml_escape(d) for d in allowed) + "]")
    else:
        lines.append("allowed_destinations = []")

    return "\n".join(lines) + "\n"


def main() -> int:
    if not CONFIG_PATH.is_file():
        sys.stderr.write(f"error: {CONFIG_PATH} not found\n")
        return 2
    try:
        tree = ET.parse(CONFIG_PATH)
    except ET.ParseError as e:
        sys.stderr.write(f"error: cannot parse {CONFIG_PATH}: {e}\n")
        return 2
    root = tree.getroot()
    client = root.find(".//OPNsense/trusttunnel/client")
    if client is None:
        sys.stderr.write("error: <OPNsense><trusttunnel><client> missing\n")
        return 1

    try:
        srv = find_active_server(client)
        OUT_DIR.mkdir(parents=True, exist_ok=True)
        os.chmod(OUT_DIR, 0o750)
        _write_atomic(OUT_FILE, render_client_toml(client, srv), 0o600)
    except (ValueError, KeyError) as e:
        sys.stderr.write(f"error: {e}\n")
        return 1
    except OSError as e:
        sys.stderr.write(f"I/O error: {e}\n")
        return 2

    print(f"rendered {OUT_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
